### ISSUE TITLE
Issue with ajax call

### ISSUE THREAD

**Issue by juantoniomac** [nabinked/NToastNotify#30] opened 2018-03-15 00:20 UTC
When I execute an ajax call everything seems to work fine, but when it should run the function success or error doesn't work.
When I debbug it in Chrome, the request show thats the "Initiator" was toastr.js, nevertheless in this part of my code I don´t call a toast.
I've been researching and it seems that toast.js is intercepting all xml request so I want to know if this could be the cause of my Issue

**Comment by nabinked** [comment] 2018-03-15 05:04
Are you saying that any normal ajax call is not hitting it's success or error callback?

**Comment by juantoniomac** [comment] 2018-03-15 15:27
This is the ajax that I'm using
`function callAjax() {
    $.ajax({
        type: "POST",
        url: "/Accesos/Index?handler=Example",
        beforeSend: function (xhr) {
            xhr.setRequestHeader("XSRF-TOKEN",
                $('input:hidden[name="__RequestVerificationToken"]').val());
        },
        data: "{text: 'text'}",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (response) {
            alert('success');
        },
        failure: function (response) {
            alert('Error');
        }
    });
}
`

The method which is called in AJAX actually is executed and if I check the request in WebBrowser I can see the Response sent it by the method, but I don't know for what reason the success or failure callbacks are not hitting.

**Comment by nabinked** [comment] 2018-03-15 23:11
I think I found where the issue is. The library is simply overriding the success handler. Should have checked before. Thanks a lot for pointing it out. I will fix this tonight and probably push a new version to Nuget. Cheers

**Comment by nabinked** [comment] 2018-03-20 11:59
Should be fixed in 5.0.0. Please confirm Thanks.

**Comment by nabinked** [comment] 2018-03-20 12:05
Beware of the breaking changes in 5.0 though. Go through the read me again

**Closed by nabinked** 2018-03-20 12:05 UTC
Labels: bug, critical
