### ISSUE TITLE
v6.0.0 - tsconfig error 

### ISSUE THREAD

**Issue by dotnetshadow** [nabinked/NToastNotify#93] opened 2019-09-25 09:23 UTC
Hi there,

I just updated to the latest version 6.0.0 and getting the following error:
`
sc : error TS18003: Build:No inputs were found in config file 'C:/Users/ffff/.nuget/packages/ntoastnotify/6.0.0/contentFiles/any/netcoreapp3.0/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","wwwroot"]'
`

I was able to use the dotnet cli to see the issue:
If I delete the **tsconfig.json** file in `contentFiles\any\netcoreapp3.0` then it runs ok
Please make sure to delete the **obj** and **bin** directory to see the error.

I believe this is a similar error to the one reported before #82 

**Solutions**
_Option 1:_
One way that seemed to work was to put an empty file.ts file in `contentFiles\any\netcoreapp3.0`.

_Option 2:_ 
I think the file shouldn't be included to begin with, it's only needed for building?
This might give a clue about how to fix the issue?
https://github.com/aspnet/Templates/issues/854

**Comment by nabinked** [comment] 2019-09-26 00:28
Ahh, I rememeber this. Need to lookup how the content packing has changed in 3.0

**Comment by dotnetshadow** [comment] 2019-09-26 00:34
No problem, I believe the simple fix would be to not include the content files when packing the package. Hopefully it's not too much work to do this

**Comment by nabinked** [comment] 2019-09-26 12:32
Please try 6.0.1 and see if thats fixed for 3.0.

**Comment by rbsdotnet** [comment] 2019-09-27 01:10
Hi,
Project error when adding new version

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0 requires Microsoft.CodeAnalysis.CSharp (= 3.0.0) but version Microsoft.CodeAnalysis.CSharp 3.3.0 was resolved.
------------------------------------------------------------------------------------

Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project

**Comment by dotnetshadow** [comment] 2019-09-27 01:11
@nabinked This package seemed to work for me

**Comment by rbsdotnet** [comment] 2019-09-29 04:52
@nabinked

.net core 3 problem solved?


Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0 requires Microsoft.CodeAnalysis.CSharp (= 3.0.0) but version Microsoft.CodeAnalysis.CSharp 3.3.0 was resolved.
Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project

**Comment by nabinked** [comment] 2019-09-29 22:24
This does not look like an issue caused by this package.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
बाट: Reza Bahari <notifications@github.com>
पठाइयो: Sunday, September 29, 2019 2:52:54 PM
प्रापक: nabinked/NToastNotify <NToastNotify@noreply.github.com>
बोधार्थ: Nabin Karki Thapa <nabin@outlook.com>; Mention <mention@noreply.github.com>
विषय: Re: [nabinked/NToastNotify] v6.0.0 - tsconfig error (#93)


@nabinked<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnabinked&data=02%7C01%7C%7Cfec37e7ea9c14426511308d74498e51a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637053295774455603&sdata=R7MbwSpmtBWVgjNqI9lor%2FF%2Bc0e%2BsqQwFLJ0PzuWR2Y%3D&reserved=0>

.net core 3 problem solved?

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0 requires Microsoft.CodeAnalysis.CSharp (= 3.0.0) but version Microsoft.CodeAnalysis.CSharp 3.3.0 was resolved.
Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project

**Comment by nabinked** [comment] 2019-10-01 00:00
Closing this. Please open a new issue as its different than the original issue and may not even be related to this package.

**Closed by nabinked** 2019-10-01 00:00 UTC
