### ISSUE TITLE
Toastr Dependency Issue

### ISSUE THREAD

**Issue by prindacerk** [nabinked/NToastNotify#24] opened 2018-02-04 07:58 UTC
It seems that when this package was upgraded from 3.0 to 4.0, the dependency for Toastr also got changed. 

In 3.0, the code @await Component.InvokeAsync("NToastNotify.Toastr") doesn't create a script that looks for Toastr at that line (which is in the Layout page). So the toastr.js can be loaded at the bottom of the layout page and it would still work without any issues.

In 4.0, this has been changed and now the that template code expects the toastr.js to be available at that line which means that toastr.js has to be included in the header instead of the bottom. Most scripts get loaded at the bottom of the page. So it would be better if this component doesn't force users to load it at the top. If the script generated works exactly as it did with 3.0, then it would be great.

Please look into the matter and update it if you feel my suggestion is appropriate.

**Comment by nabinked** [comment] 2018-02-04 09:15
Yes I understood. There was a definitely a lot of changes in this version. I should be able to push a new version to Nuget with a fix. Sorry for the inconvenience.

**Comment by nabinked** [comment] 2018-02-04 09:30
Are you able to produce this case ? Because I see it has no effect whether you load your scripts before the ViewComponent or after. It waits for the DOMContentLoaded event before trying to use the toastr library to show notifications. I see no issues here. Please correct me if I am wrong. I have pushed a new commit 3548fcc to master with a similar case in the [NToastNotify.Web.FeatureFolders](https://github.com/nabinked/NToastNotify/blob/master/sample/NToastNotify.Web.FeatureFolders/Features/Shared/_Layout.cshtml) sample project and see no problems.

**Comment by prindacerk** [comment] 2018-02-04 09:49
Maybe I misunderstood the instructions. When you have said to place `@await Component.InvokeAsync("NToastNotify.Toastr")` in Layout page, is it after the Scripts section? I placed it at the top of the body section because I thought it must be placed where the notification is supposed to appear. Maybe moving it to the bottom would work.

I didn't have the issue on V3.0. It only started appearing after V4.0 update.

**Comment by nabinked** [comment] 2018-02-04 10:51
You can place that line anywhere between ```head``` or ```body``` tag. 
I am unable to reproduce this issue. If you can show me how to reproduce, I would be able to see what the issue is.

**Comment by nabinked** [comment] 2018-02-07 09:36
Were you able to fix your issue ? When you upgraded to 4.0. Did you also add NToastNotify as a middleware inside the Configure function in startup ?  Please check the [release note](https://github.com/nabinked/NToastNotify/releases/tag/4.0.0) on how to upgrade.

**Comment by prindacerk** [comment] 2018-02-07 09:59
Hi,
You're correct. I missed the middleware. Once I set that, the error message I mentioned is gone now.

However, I am getting a different error message now. 
`Refused to get unsafe header "NToastNotify-Messages"`
Didn't get that with 3.0. Do you know why this is popping up now?

**Comment by nabinked** [comment] 2018-02-07 10:33
Interesting. What browser is it ?

**Comment by nabinked** [comment] 2018-02-07 10:34
Thax AJAX message transportation is done using custom response headers.

**Comment by prindacerk** [comment] 2018-02-07 10:35
Chrome.

On 7 Feb. 2018 21:33, "Nabin Karki Thapa" <notifications@github.com> wrote:

Interesting. What browser is it ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nabinked/NToastNotify/issues/24#issuecomment-363726654>,
or mute the thread

**Comment by prindacerk** [comment] 2018-02-07 10:37
I am not posting custom response. And this message appears as soon as the
page is loaded. Not on any specific toastr message response.

I however don't face this issue in your demo app. Only in 4 of my projects.
All have this. It didn't appear previously on 3.0.

Kind Regards,
JB

**Comment by nabinked** [comment] 2018-02-07 12:18
Thank for the details .
I will really have to do some thorough testing on the 4.0. 
Are you on localhost? or is it deployed somewhere?

**Comment by prindacerk** [comment] 2018-02-07 12:30
Localhost. Project is running in .Net Core 2.0.

**Comment by nabinked** [comment] 2018-02-07 20:56
Could you please use the 4.0.3 version and see if that issues goes away ?

**Comment by prindacerk** [comment] 2018-02-21 11:12
Sorry I didn't have the time until now. Just checked 4.0.4 and it still has the issue. See attached. It is happening on page load.

![image](https://user-images.githubusercontent.com/4536573/36477116-2963959c-1754-11e8-8b67-6f2f6bf22ce1.png)

**Comment by nabinked** [comment] 2018-03-11 04:04
closing this and tracking the unsafe header issue at #28

**Closed by nabinked** 2018-03-11 04:04 UTC
