### ISSUE TITLE
Cannot call ViewComponent after updating to 2.0.2

### ISSUE THREAD

**Issue by os1r1s110** [nabinked/NToastNotify#11] opened 2017-06-15 13:55 UTC
I don't know if the problem only arises on my side but since I updated to 2.0.2, I get an ArgumentNullException when invoking the VC....

Could you verify on your side if it does the same?

**Comment by os1r1s110** [comment] 2017-06-15 14:11
Okay I'm really not sure if that's the only problem but it seems like adding the ``` exit 0; ``` line to the nugetpush.bat script resolves the issue....

**Comment by nabinked** [comment] 2017-06-15 22:16
I could not reproduce this error. I don't think there is any connection between the bat file and the component. Its a weird issue. But however I did find a new issue causing NullPointerException in the ToastrView.cshtml when the ToastMessages were null  and fixed with new commits pushed it to master and nugget version 2.0.3. I hope its all good now.

**Closed by nabinked** 2017-06-15 22:16 UTC

**Comment by os1r1s110** [comment] 2017-06-16 11:17
Okay, thanks for fixing the bug you found. You were not forced to merge the fix if it was not related though ahah :P

**Comment by nabinked** [comment] 2017-06-16 11:22
Haha. It was one line of code. What could possibly go wrong ? :p

**Comment by os1r1s110** [comment] 2017-06-16 11:57
We never know lol. As I said in the first comment, I really didn't know if it was the source of the error. I just looked in the commits between my merged PR and the version you published and there were not much changes that could give me the error I got and as soon as I reverted the line removal, everything built just fine... so I guessed that was it :) 

But I know nothing about .bat script so I could be totally wrong and just be super lucky (I doubt it though hehe)

Anyways, I'll download the latest version today and check if everything works as expected (at least to my point of view I guess )

**Comment by nabinked** [comment] 2017-06-16 21:19
Yes. that bring me to the point. Definitely deed to write Unit Tests for the project now.

**Comment by os1r1s110** [comment] 2017-06-16 21:44
Could not agree more, I need to do it more in my projects too (never really did in a meaningful way but now I'm working on a big project and I really see the need for multiple testing types (unit, integration, regression, etc...) but that's no easy task in a single man team ahaha :P

**Comment by nabinked** [comment] 2017-06-17 02:52
True
